### ISSUE TITLE
Segmentation fault when reporting results (0.6.0)

### ISSUE THREAD

**Issue by vals** [COMBINE-lab/salmon#34]
I was just trying out the new version. It seems to be working, but it seems to fail at the time of printing results.

Here's a tail of the text output:
```
[2016-01-02 00:08:48.445] [jointLog] [info] Computed 66783 rich equivalence classes for further processing
[2016-01-02 00:08:48.445] [jointLog] [info] Counted 2977936 total reads in the equivalence classes
[2016-01-02 00:08:54.862] [jointLog] [warning] Only 2977936 fragments were mapped, but the number of burn-in fragments was set to 5000000.
The effective lengths have been computed using the observed mappings.

[2016-01-02 00:08:54.862] [jointLog] [warning] Since only 2977936 (< 5000000) fragments were observed, modeling of the fragment start position distribution has been disabled
[2016-01-02 00:08:54.862] [jointLog] [info] Mapping rate = 48.8134%

[2016-01-02 00:08:54.862] [jointLog] [info] finished quantifyLibrary()
[2016-01-02 00:08:54.863] [jointLog] [info] Starting optimizer
[2016-01-02 00:08:54.918] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2016-01-02 00:08:54.921] [jointLog] [info] iteration = 0 | max rel diff. = 48.4964
[2016-01-02 00:08:55.024] [jointLog] [info] iteration 50, recomputing effective lengths
[2016-01-02 00:08:57.626] [jointLog] [info] iteration = 100 | max rel diff. = 0.157189
[2016-01-02 00:08:57.835] [jointLog] [info] iteration = 200 | max rel diff. = 0.0984302
[2016-01-02 00:08:58.048] [jointLog] [info] iteration = 300 | max rel diff. = 0.0774471
[2016-01-02 00:08:58.265] [jointLog] [info] iteration = 400 | max rel diff. = 0.0866256
[2016-01-02 00:08:58.472] [jointLog] [info] iteration 500, recomputing effective lengths
[2016-01-02 00:09:00.486] [jointLog] [info] iteration = 500 | max rel diff. = 0.0216284
[2016-01-02 00:09:00.696] [jointLog] [info] iteration = 600 | max rel diff. = 0.0269734
[2016-01-02 00:09:00.905] [jointLog] [info] iteration = 700 | max rel diff. = 0.0166003
[2016-01-02 00:09:01.113] [jointLog] [info] iteration = 800 | max rel diff. = 0.0136659
[2016-01-02 00:09:01.334] [jointLog] [info] iteration = 900 | max rel diff. = 0.0114614
[2016-01-02 00:09:01.542] [jointLog] [info] iteration 1000, recomputing effective lengths
[2016-01-02 00:09:03.495] [jointLog] [info] iteration = 1000 | max rel diff. = 0.0102234
[2016-01-02 00:09:03.716] [jointLog] [info] iteration = 1100 | max rel diff. = 0.0202324
[2016-01-02 00:09:03.929] [jointLog] [info] iteration = 1200 | max rel diff. = 0.010957
[2016-01-02 00:09:03.946] [jointLog] [info] iteration = 1209 | max rel diff. = 0.00996627
[2016-01-02 00:09:03.952] [jointLog] [info] Finished optimizer
[2016-01-02 00:09:03.952] [jointLog] [info] writing output

Computing gene-level abundance estimates
[2016-01-02 00:09:04.141] [jointLog] [warning] NOTE: Read Lib [( /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/ERP009633_cell20_1.fastq, /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/ERP009633_cell20_2.fastq )] :

Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: /tmp/ERP009633_cell20_salmon_out/libFormatCounts.txt for details

There were 104534 transcripts mapping to 44034 genes
Parsed 104000 expression lines
done
Aggregating expressions to gene level . . . done
Segmentation fault (core dumped)
```

**Comment by rob-p** [comment]
Hrmm --- so at this point the transcript-level estimates have been written.  It seems there is some issue with the aggregation to the gene level.  My guess is something awry with its interpretation of the gtf file.  If you can share the data, I can try and reproduce the issue and see where the problem is.

**Comment by vals** [comment]
The aggregation works, and I get the same problem when not providing a gene map. 

Both quant.sf and quant.genes.sf are actually written. The segfault must be upon exit or something.

**Comment by rob-p** [comment]
Ok; that's strange b/c I'm not getting segfaults on either the version compiled from source or the debian binary (I'm assuming your on Linux).  Would it be possible to share the data that's causing this issue?

**Comment by rob-p** [comment]
Hrmm --- I take that back!  I get the segfault with the pre-compiled version (but not the version compiled from source!).  And, as you say, it seems to write out the results correctly.  I'll take a look and report back here.

**Comment by vals** [comment]
Oh, great, was making a small example data set. I'll stop that then.

I was trying to compile, but I can't get Boost installed with linuxbrew for some reason.

**Comment by rob-p** [comment]
Still looking, but this is very strange!  It happens when the program is exiting, during the destruction of some objects.  Strangely, it doesn't happen on the test data (also it's strange that it doesn't happen in the version compiled from source).

**Comment by rob-p** [comment]
The segfault seems to be happening with Jemalloc (an external dependency).  I'm going to see if switching to tcmalloc in the binary build fixes it.

**Comment by rob-p** [comment]
OK --- I think I fixed it; can you re-download the v0.6.0 binary and see if the segfault goes away for you?  I think it was the result of failing to give a particular class a default constructor --- a certain variable was being initialized properly on my newer compiler, but that was not the case on the older compiler on the VM where I build the binary.  If this resolves the issue for you, I'll probably bump to v0.6.1 just in case anyone tries to build from the source tarball on an older compiler.

**Comment by vals** [comment]
I just redownloaded and extracted and tried again, and unfortunately the problem persists =/

```
...
[2016-01-02 17:47:51.342] [jointLog] [info] iteration = 1600 | max rel diff. = 0.0133376
[2016-01-02 17:47:51.443] [jointLog] [info] iteration = 1630 | max rel diff. = 0.00771098
[2016-01-02 17:47:51.447] [jointLog] [info] Finished optimizer
[2016-01-02 17:47:51.448] [jointLog] [info] writing output

Computing gene-level abundance estimates
[2016-01-02 17:47:51.678] [jointLog] [warning] NOTE: Read Lib [( /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_1.fastq, /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_2.fastq )] :

Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: SRP057125_SRS936134_salmon_out/libFormatCounts.txt for details

There were 104534 transcripts mapping to 44034 genes
Parsed 104000 expression lines
done
Aggregating expressions to gene level . . . done
Segmentation fault (core dumped)
```

If you want I can upload index and a couple of fastq files somewhere so you can try?

**Comment by rob-p** [comment]
Sure --- since, at this point, I don't seem able to reproduce the issue any more.  Just for a sanity check, can you md5sum the binary you have?  I have `fc39599b6c027eb97bb2f4c7bdd361f3`.

**Comment by vals** [comment]
That's the same md5sum as I have:

```
[vale@ebi-003 bin]$ pwd
/nfs/research2/teichmann/tools/SalmonBeta-0.6.0_DebianSqueeze/bin
[vale@ebi-003 bin]$ md5sum salmon
fc39599b6c027eb97bb2f4c7bdd361f3  salmon
```

**Comment by rob-p** [comment]
OK --- very strange.  I've been testing it out on different data and have been unable to reproduce the segfault.  I'll try on your dataset when it's ready to see if the problem pops up.  I actually hope it does, because it will be a very tricky bug to fix if it only happens on certain hosts!

**Comment by vals** [comment]
It gets stranger... I prepared a public directory with the files I use and made a bash script to reproduce the run of salmon. This directory is in my home folder, and has symlinks to the actual NFS locations of the files: http://www.ebi.ac.uk/~vale/salmon-problem/

```
[vale@ebi-003 salmon-problem]$ ls -lh
total 20K
lrwxrwxrwx 1 vale rst_pub   96 Jan  2 20:09 mouse_cdna_38.p3.78_repbase_ercc.fa -> /nfs/research2/teichmann/reference/mus-musculus/salmon/quasi/mouse_cdna_38.p3.78_repbase_ercc.fa
-rw-rw-r-- 1 vale rst_pub  301 Jan  2 20:19 run_salmon.sh
lrwxrwxrwx 1 vale rst_pub  112 Jan  2 20:08 SRP057125_SRS936134_1.fastq -> /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_1.fastq
lrwxrwxrwx 1 vale rst_pub  112 Jan  2 20:08 SRP057125_SRS936134_2.fastq -> /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_2.fastq
drwxrwxr-x 5 vale rst_pub 4.0K Jan  2 20:20 SRP057125_SRS936134_salmon_out
```

But when I run the script there, it succeeds, without segfault.

```
[vale@ebi-003 salmon-problem]$ bash run_salmon.sh
Version Info: This is the most recent version of Salmon.
# salmon (mapping-based) v0.6.0
# [ program ] => salmon
# [ command ] => quant
# [ index ] => { mouse_cdna_38.p3.78_repbase_ercc.fa }
# [ libType ] => { IU }
# [ mates1 ] => { SRP057125_SRS936134_1.fastq }
# [ mates2 ] => { SRP057125_SRS936134_2.fastq }
# [ output ] => { SRP057125_SRS936134_salmon_out }
# [ biasCorrect ] => { }
# [ useFSPD ] => { }
Logs will be written to SRP057125_SRS936134_salmon_out/logs
[2016-01-02 20:16:39.349] [jointLog] [info] parsing read library format
there is 1 lib
Loading 32-bit quasi index[2016-01-02 20:16:39.895] [stderrLog] [info] Loading Suffix Array
[2016-01-02 20:16:39.895] [stderrLog] [info] Loading Position Hash
[2016-01-02 20:16:39.894] [jointLog] [info] Loading Quasi index
[2016-01-02 20:16:42.565] [stderrLog] [info] Loading Transcript Info
[2016-01-02 20:16:43.654] [stderrLog] [info] Loading Rank-Select Bit Array
[2016-01-02 20:16:44.075] [stderrLog] [info] There were 104534 set bits in the bit array
[2016-01-02 20:16:44.448] [stderrLog] [info] Computing transcript lengths
[2016-01-02 20:16:44.448] [stderrLog] [info] Waiting to finish loading hash
Index contained 104534 targets
[2016-01-02 20:16:57.606] [stderrLog] [info] Done loading index
[2016-01-02 20:16:57.606] [jointLog] [info] done



processed 12000000 fragments
hits: 24367197, hits per frag:  2.06194+06







[2016-01-02 20:17:29.841] [jointLog] [info] Computed 102251 rich equivalence classes for further processing
[2016-01-02 20:17:29.841] [jointLog] [info] Counted 10033689 total reads in the equivalence classes
[2016-01-02 20:17:29.867] [jointLog] [info] Mapping rate = 83.0244%

[2016-01-02 20:17:29.867] [jointLog] [info] finished quantifyLibrary()
[2016-01-02 20:17:29.867] [jointLog] [info] Starting optimizer
[2016-01-02 20:17:30.130] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2016-01-02 20:17:30.136] [jointLog] [info] iteration = 0 | max rel diff. = 65.1271
[2016-01-02 20:17:30.315] [jointLog] [info] iteration 50, recomputing effective lengths
[2016-01-02 20:17:32.978] [jointLog] [info] iteration = 100 | max rel diff. = 0.259134
[2016-01-02 20:17:33.312] [jointLog] [info] iteration = 200 | max rel diff. = 0.136762
[2016-01-02 20:17:33.659] [jointLog] [info] iteration = 300 | max rel diff. = 0.0544656
[2016-01-02 20:17:33.979] [jointLog] [info] iteration = 400 | max rel diff. = 0.0635573
[2016-01-02 20:17:34.298] [jointLog] [info] iteration 500, recomputing effective lengths
[2016-01-02 20:17:36.486] [jointLog] [info] iteration = 500 | max rel diff. = 0.747925
[2016-01-02 20:17:36.865] [jointLog] [info] iteration = 600 | max rel diff. = 0.0480446
[2016-01-02 20:17:37.236] [jointLog] [info] iteration = 700 | max rel diff. = 0.0231505
[2016-01-02 20:17:37.634] [jointLog] [info] iteration = 800 | max rel diff. = 0.0147497
[2016-01-02 20:17:38.031] [jointLog] [info] iteration = 900 | max rel diff. = 0.0147943
[2016-01-02 20:17:38.421] [jointLog] [info] iteration 1000, recomputing effective lengths
[2016-01-02 20:17:40.612] [jointLog] [info] iteration = 1000 | max rel diff. = 0.0146819
[2016-01-02 20:17:40.968] [jointLog] [info] iteration = 1100 | max rel diff. = 0.021278
[2016-01-02 20:17:41.343] [jointLog] [info] iteration = 1200 | max rel diff. = 0.0188351
[2016-01-02 20:17:41.695] [jointLog] [info] iteration = 1300 | max rel diff. = 0.0115257
[2016-01-02 20:17:42.020] [jointLog] [info] iteration = 1400 | max rel diff. = 0.019727
[2016-01-02 20:17:42.346] [jointLog] [info] iteration = 1500 | max rel diff. = 0.0290858
[2016-01-02 20:17:42.679] [jointLog] [info] iteration = 1600 | max rel diff. = 0.0100559
[2016-01-02 20:17:42.993] [jointLog] [info] iteration = 1700 | max rel diff. = 0.0101365
[2016-01-02 20:17:43.314] [jointLog] [info] iteration = 1800 | max rel diff. = 0.0100707
[2016-01-02 20:17:43.650] [jointLog] [info] iteration = 1900 | max rel diff. = 0.0100722
[2016-01-02 20:17:43.933] [jointLog] [info] iteration = 1990 | max rel diff. = 0.00542674
[2016-01-02 20:17:43.937] [jointLog] [info] Finished optimizer
[2016-01-02 20:17:43.937] [jointLog] [info] writing output

[2016-01-02 20:17:44.160] [jointLog] [warning] NOTE: Read Lib [( SRP057125_SRS936134_1.fastq, SRP057125_SRS936134_2.fastq )] :

Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: SRP057125_SRS936134_salmon_out/libFormatCoun                                                                                   ts.txt for details

[vale@ebi-003 salmon-problem]$
```

The command run being:
```
salmon quant \
-i mouse_cdna_38.p3.78_repbase_ercc.fa \
-l IU \
-1 SRP057125_SRS936134_1.fastq \
-2 SRP057125_SRS936134_2.fastq \
-o SRP057125_SRS936134_salmon_out \
-g /nfs/research2/teichmann/reference/mus-musculus/salmon/mouse_cdna38.78_repbase_ercc_index_gene_map.txt \
--biasCorrect \
--useFSPD
```

But if I instead run salmon in the NFS directory where I want to run it, the core dumps...

```
[vale@ebi-003 mouse]$ salmon quant \
>         -i /nfs/research2/teichmann/reference/mus-musculus/salmon/quasi/mouse_cdna_38.p3.78_repbase_ercc.fa \
>         -l IU \
>         -1 /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_1.fastq \
>         -2 /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_2.fastq \
>         -o SRP057125_SRS936134_salmon_out \
>         -g /nfs/research2/teichmann/reference/mus-musculus/salmon/mouse_cdna38.78_repbase_ercc_index_gene_map.txt \
>         --biasCorrect \
>         --useFSPD
Version Info: This is the most recent version of Salmon.
# salmon (mapping-based) v0.6.0
# [ program ] => salmon
# [ command ] => quant
# [ index ] => { /nfs/research2/teichmann/reference/mus-musculus/salmon/quasi/mouse_cdna_38.p3.78_repbase_ercc.fa }
# [ libType ] => { IU }
# [ mates1 ] => { /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_1.fastq }
# [ mates2 ] => { /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_2.fastq }
# [ output ] => { SRP057125_SRS936134_salmon_out }
# [ geneMap ] => { /nfs/research2/teichmann/reference/mus-musculus/salmon/mouse_cdna38.78_repbase_ercc_index_gene_map.txt }
# [ biasCorrect ] => { }
# [ useFSPD ] => { }
Logs will be written to SRP057125_SRS936134_salmon_out/logs
[2016-01-02 20:22:59.800] [jointLog] [info] parsing read library format
there is 1 lib
Loading 32-bit quasi index[2016-01-02 20:23:00.830] [stderrLog] [info] Loading Suffix Array
[2016-01-02 20:23:00.830] [stderrLog] [info] Loading Position Hash
[2016-01-02 20:23:00.829] [jointLog] [info] Loading Quasi index
[2016-01-02 20:23:03.751] [stderrLog] [info] Loading Transcript Info
[2016-01-02 20:23:04.776] [stderrLog] [info] Loading Rank-Select Bit Array
[2016-01-02 20:23:05.009] [stderrLog] [info] There were 104534 set bits in the bit array
[2016-01-02 20:23:05.325] [stderrLog] [info] Computing transcript lengths
[2016-01-02 20:23:05.325] [stderrLog] [info] Waiting to finish loading hash
Index contained 104534 targets
[2016-01-02 20:23:16.571] [stderrLog] [info] Done loading index
[2016-01-02 20:23:16.571] [jointLog] [info] done



processed 12000001 fragments
hits: 24367128, hits per frag:  2.04044







[2016-01-02 20:23:49.850] [jointLog] [info] Computed 102251 rich equivalence classes for further processing
[2016-01-02 20:23:49.850] [jointLog] [info] Counted 10033689 total reads in the equivalence classes
[2016-01-02 20:23:49.875] [jointLog] [info] Mapping rate = 83.0244%

[2016-01-02 20:23:49.875] [jointLog] [info] finished quantifyLibrary()
[2016-01-02 20:23:49.875] [jointLog] [info] Starting optimizer
[2016-01-02 20:23:50.378] [jointLog] [info] Marked 0 weighted equivalence classes as degenerate
[2016-01-02 20:23:50.382] [jointLog] [info] iteration = 0 | max rel diff. = 64.9993
[2016-01-02 20:23:50.584] [jointLog] [info] iteration 50, recomputing effective lengths
[2016-01-02 20:23:53.386] [jointLog] [info] iteration = 100 | max rel diff. = 0.263028
[2016-01-02 20:23:53.777] [jointLog] [info] iteration = 200 | max rel diff. = 0.13921
[2016-01-02 20:23:54.171] [jointLog] [info] iteration = 300 | max rel diff. = 0.0536404
[2016-01-02 20:23:54.564] [jointLog] [info] iteration = 400 | max rel diff. = 0.063039
[2016-01-02 20:23:54.954] [jointLog] [info] iteration 500, recomputing effective lengths
[2016-01-02 20:23:57.205] [jointLog] [info] iteration = 500 | max rel diff. = 0.748653
[2016-01-02 20:23:57.662] [jointLog] [info] iteration = 600 | max rel diff. = 0.0535482
[2016-01-02 20:23:58.058] [jointLog] [info] iteration = 700 | max rel diff. = 0.0180352
[2016-01-02 20:23:58.440] [jointLog] [info] iteration = 800 | max rel diff. = 0.0162171
[2016-01-02 20:23:58.826] [jointLog] [info] iteration = 900 | max rel diff. = 0.0146915
[2016-01-02 20:23:59.212] [jointLog] [info] iteration 1000, recomputing effective lengths
[2016-01-02 20:24:01.395] [jointLog] [info] iteration = 1000 | max rel diff. = 0.0147088
[2016-01-02 20:24:01.837] [jointLog] [info] iteration = 1100 | max rel diff. = 0.021175
[2016-01-02 20:24:02.193] [jointLog] [info] iteration = 1200 | max rel diff. = 0.01904
[2016-01-02 20:24:02.572] [jointLog] [info] iteration = 1300 | max rel diff. = 0.0187047
[2016-01-02 20:24:02.972] [jointLog] [info] iteration = 1400 | max rel diff. = 0.0213549
[2016-01-02 20:24:03.360] [jointLog] [info] iteration = 1500 | max rel diff. = 0.0311727
[2016-01-02 20:24:03.745] [jointLog] [info] iteration = 1600 | max rel diff. = 0.0100658
[2016-01-02 20:24:04.141] [jointLog] [info] iteration = 1700 | max rel diff. = 0.0100679
[2016-01-02 20:24:04.536] [jointLog] [info] iteration = 1800 | max rel diff. = 0.0100686
[2016-01-02 20:24:04.642] [jointLog] [info] iteration = 1827 | max rel diff. = 0.00921912
[2016-01-02 20:24:04.646] [jointLog] [info] Finished optimizer
[2016-01-02 20:24:04.646] [jointLog] [info] writing output

Computing gene-level abundance estimates
[2016-01-02 20:24:04.882] [jointLog] [warning] NOTE: Read Lib [( /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_1.fastq, /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_2.fastq )] :

Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: SRP057125_SRS936134_salmon_out/libFormatCounts.txt for details

There were 104534 transcripts mapping to 44034 genes
Parsed 104000 expression lines
done
Aggregating expressions to gene level . . . done
Segmentation fault (core dumped)
[vale@ebi-003 mouse]$
```

(I also tried the command in the NSF directory to write to /tmp/SRP057125_SRS936134_salmon_out, but that also segfaults)

**Comment by rob-p** [comment]
Argghh --- that's gonna be a thinker.  Can you try running it under GDB?

```
$ gdb salmon
(gdb) r quant \
-i mouse_cdna_38.p3.78_repbase_ercc.fa \
-l IU \
-1 SRP057125_SRS936134_1.fastq \
-2 SRP057125_SRS936134_2.fastq \
-o SRP057125_SRS936134_salmon_out \
-g /nfs/research2/teichmann/reference/mus-musculus/salmon/mouse_cdna38.78_repbase_ercc_index_gene_map.txt \
--biasCorrect \
--useFSPD
```

when it segfaults, you can issue the `bt` command to at least see where.  If its still inside of JeMalloc, I can build another binary with just the standard allocator to see if the problem persists there (its strange that it depends on where the file is coming from! I don't have any NFS mounts either to test on).

**Comment by vals** [comment]
Especially since the files in both cases actually are in the same location... I could imagine it being an issue with something going write with the communication over the NFS. But in the working case it's just links to the same NFS location.

Here is the tail of the gdb output:
```
Computing gene-level abundance estimates
[2016-01-02 21:56:43.793] [jointLog] [warning] NOTE: Read Lib [( /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_1.fastq, /nfs/research2/teichmann/valentine/detection-comparison/salmon0.4.2-comparison/mouse/SRP057125_SRS936134_2.fastq )] :

Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: SRP057125_SRS936134_salmon_out/libFormatCounts.txt for details

There were 104534 transcripts mapping to 44034 genes
Parsed 104000 expression lines
done
Aggregating expressions to gene level . . . done

Program received signal SIGSEGV, Segmentation fault.
0x000000320dc093a0 in pthread_mutex_lock () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64
(gdb) bt
#0  0x000000320dc093a0 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x0000000000806370 in je_tcache_bin_flush_small () at include/jemalloc/internal/mutex.h:85
#2  0x0000000000806c60 in je_tcache_event_hard () at src/tcache.c:44
#3  0x00000000005915fc in std::vector<Transcript, std::allocator<Transcript> >::~vector() ()
#4  0x00000000005941c6 in ReadExperiment::~ReadExperiment() ()
#5  0x00000000005872ce in salmonQuantify(int, char**) ()
#6  0x0000000000514472 in main ()
(gdb)
```

It does indeed seem to be inside JeMalloc.

**Comment by rob-p** [comment]
Hi @vals --- here is a version compiled with tcmalloc instead of jemalloc.  Let me know if this helps at all.  If you're still seeing this issue, I'll try one with vanilla malloc.

[SalmonBeta-0.6.0_DebianSqueeze_tcmalloc.tar.gz](https://github.com/COMBINE-lab/salmon/files/76427/SalmonBeta-0.6.0_DebianSqueeze_tcmalloc.tar.gz)

**Comment by vals** [comment]
This version seem to work without any issues!

**Comment by rob-p** [comment]
Cool!  I'll post this under releases with a brief note when I get home.  I'll probably leave both binaries under the releases.  I'm still very curious what's up with jemalloc!

**Comment by rob-p** [comment]
Hi @vals,
  I'm still trying to track down this bug and figure out why it occurred in the first place.  I've been working on a different way to deal with reclaiming the resources that caused the problem before and was wondering if you'd be willing to test the attached binary to see if it still segfaults on your data. 
 Thanks! [SalmonBeta-0.6.1_DebianSqueeze.tar.gz](https://github.com/COMBINE-lab/salmon/files/87914/SalmonBeta-0.6.1_DebianSqueeze.tar.gz)
